### ISSUE TITLE
Github Actions Billable Minutes Optimisation

### ISSUE THREAD

**Issue by angeloskaltsikis** [transcend-io/terragrunt-atlantis-config-github-action#1]
Hey its me again Angelos!
I want to thank you @dmattia once again for your prompt responses.
So after trying the current implementation of the github action i can take that it took around 1 minutes 24seconds to run which translates to 70sec of billable github actions minutes.
I was thinking ways to try to optimise the current github action to not run the actual generation unless there are changes introduced.
I would suggest 2 changes straight away:
1) Update the example to be triggered on `pull_request` which seems to fit better to the case and avoids running the action to all branches
2) Use [those](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths) path selectors to run the github action when `terragrunt.hcl` files have been changed.

Any other ideas are welcome 😄

**Comment by dmattia** [comment]
Ooh very cool, I'm very new to Github Actions so I hadn't seen those docs. I'll make these updates soon
